# Generated by Django 5.0.2 on 2024-02-28 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_variation_category', models.CharField(blank=True, choices=[('size', 'size'), ('colour', 'colour'), ('fabric', 'fabric'), ('weight', 'weight'), ('dimensions', 'dimensions')], max_length=100)),
                ('iphone_case_variation_category', models.CharField(blank=True, choices=[('colour', 'colour'), ('phone_model', 'phone_model')], max_length=100)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
