# Generated by Django 5.0.2 on 2024-02-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_variation_iphone_case_variation_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='clothes_variation_category',
            new_name='variation_category',
        ),
    ]
