# Generated by Django 5.0.2 on 2024-03-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
